resources:
    - name: ((spring_bootcamp_repo))
      type: git
      source: 
        uri: https://github.com/pivot-carlos-poon/device-management.git
        branch: master
    - name: pws-labs-playground
      type: cf
      source:
        api: https://api.run.pivotal.io
        username: ((pws_email))
        password: ((pws_password))
        organization: ((pws_org))
        space: ((pws_space))
        skip_cert_check: true

jobs: 
  - name: build
    plan:
      - get: ((spring_bootcamp_repo))
        trigger: true
      - task: unit-build
        file: ((spring_bootcamp_repo))/ci/unit-build/device-controller-build.yml 
        params: 
          INPUT_RESOURCE: ((spring_bootcamp_repo))

  - name: controller-test
    plan:
      - get: ((spring_bootcamp_repo))
        trigger: true
      - task: unit-test
        file: ((spring_bootcamp_repo))/ci/test/device-controller-test.yml
        params: 
          INPUT_RESOURCE: ((spring_bootcamp_repo))

  - name: deploy
    plan:
        - get: ((spring_bootcamp_repo))
          passed: [build, controller-test]
          trigger: true
        - task: unit-deploy
          file: ((spring_bootcamp_repo))/ci/test/device-controller-test.yml
          params: 
            INPUT_RESOURCE: ((spring_bootcamp_repo))          
        - put: pws-labs-playground
          params:
            manifest: ./((spring_bootcamp_repo))/ci/manifest.yml
