resources:
    - name: ((spring_bootcamp_repo))
      type: git
      source: 
        uri: https://github.com/pivot-carlos-poon/device-management.git
        branch: master
    - name: pws-labs-playground
      type: cf
      source:
        api: https://api.run.pivotal.io
        username: ((pws_email))
        password: ((pws_password))
        organization: ((pws_org))
        space: ((pws_space))
        skip_cert_check: true

jobs: 
  - name: build
    plan:
      - get: ((spring_bootcamp_repo))
        trigger: true
      - task: unit-build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: openjdk, tag: "8-jdk"}
          inputs: 
            - name: ((spring_bootcamp_repo))
          run:
            path: ((spring_bootcamp_repo))/ci/unit-build/device-controller-build.sh
        params: 
          INPUT_RESOURCE: ((spring_bootcamp_repo))

  - name: controller-test
    plan:
      - get: ((spring_bootcamp_repo))
        trigger: true
      - task: unit-test
        # file: ((spring_bootcamp_repo))/ci/test/device-controller-test.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: openjdk, tag: "8-jdk"}
          inputs: 
            - name: ((spring_bootcamp_repo))
          run:
            path: ((spring_bootcamp_repo))/ci/test/device-controller-test.sh
        params: 
          INPUT_RESOURCE: ((spring_bootcamp_repo))

  - name: deploy
    plan:
        - get: ((spring_bootcamp_repo))
          passed: [build, controller-test]
          trigger: true
        - task: unit-deploy
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: openjdk, tag: "8-jdk"}
            inputs: 
              - name: ((spring_bootcamp_repo))
            outputs:
              - name: device-package
            run:
              path: ((spring_bootcamp_repo))/ci/deploy/device-controller-deploy.sh
          params: 
            INPUT_RESOURCE: ((spring_bootcamp_repo))          
        - put: pws-labs-playground
          params:
            manifest: ./((spring_bootcamp_repo))/ci/manifest.yml
